import github from "../assets/icons/github.png";
import instagram from "../assets/icons/instagram.png";
import linkedin from "../assets/icons/linkedin.png";
import html from "../assets/icons/html.png";
import css from "../assets/icons/css.png";
import javascript from "../assets/icons/javascript.png";
import reactjs from "../assets/icons/reactjs.png";
import nextjs from "../assets/icons/nextjs.png";
import redux from "../assets/icons/redux.png";
import nodejs from "../assets/icons/nodejs.png";
import expressjs from "../assets/icons/express.png";
import mongodb from "../assets/icons/mongodb.png";
import postgresql from "../assets/icons/postgres.png";
import git from "../assets/icons/git.png";
import adobexd from "../assets/icons/adobexd.png";
import figma from "../assets/icons/figma.png";
import tailwind from "../assets/icons/tailwindcss.png";
import mysql from "../assets/icons/mysql.png";
import reactnative from "../assets/icons/reactnative.png";
import typescript from "../assets/icons/typescript.png";
import arrowLeft from "../assets/icons/arrow-left.png";
import arrowRight from "../assets/icons/arrow-right.png";

export const githubIcon = { src: github, name: "GitHub" };
export const instagramIcon = instagram;
export const linkedinIcon = linkedin;
export const htmlIcon = { src: html, name: "HTML" };
export const cssIcon = { src: css, name: "CSS" };
export const javascriptIcon = { src: javascript, name: "JavaScript" };
export const reactjsIcon = { src: reactjs, name: "ReactJs" };
export const nextjsIcon = { src: nextjs, name: "NextJs" };
export const reduxIcon = { src: redux, name: "Redux" };
export const nodejsIcon = { src: nodejs, name: "NodeJs" };
export const expressjsIcon = { src: expressjs, name: "ExpressJs" };
export const mongodbIcon = { src: mongodb, name: "MongoDB" };
export const postgresqlIcon = { src: postgresql, name: "PostgreSQL" };
export const gitIcon = { src: git, name: "Git" };
export const adobexdIcon = { src: adobexd, name: "AdobeXD" };
export const figmaIcon = { src: figma, name: "Figma" };
export const tailwindIcon = { src: tailwind, name: "TailwindCSS" };
export const mysqlIcon = { src: mysql, name: "MySQL" };
export const reactnativeIcon = { src: reactnative, name: "React Native" };
export const typescriptIcon = { src: typescript, name: "TypeScript" };
export const arrowLeftIcon = { src: arrowLeft, name: "Arrow Left" };
export const arrowRightIcon = { src: arrowRight, name: "Arrow Right" };
